sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
    database: 0
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t8uF9GNJLBWWrssa7Gs
    access-key-secret: m6BUKnSzQCIsg2noRGEp6Akq8IJRQd
    bucket-name: java-sky-z
#  AccessKey ID
#  LTAI5t8uF9GNJLBWWrssa7Gs
#
#  AccessKey Secret
#  m6BUKnSzQCIsg2noRGEp6Akq8IJRQd